### ISSUE TITLE
FYI: emacs28 works like a dream 

### ISSUE THREAD

**Issue by chewxy** [glycerine/gopls-emacs-how-to#1]
emacs28 + nativecomp + libjansson makes gopls works very well. This was after a year of complaining on emacs 27.1 + nativecomp and libjansson. I gotta try `eglot` tho. Thanks for that

**Comment by glycerine** [comment]
interesting. thanks @chewxy

**Comment by chewxy** [comment]
eglot is really much better for my workflow. Thanks.
